// gauss_lut: 32-bit uniform word -> fixed-point approximately-Gaussian z.
//
// Bit-accurate reference: model/gauss_lut.py (mode "rom"). The ROM contents
// (positive half-table) are generated by that script into
// rtl/generated/gauss_lut_rom.sv; regenerate whenever ADDR_BITS / OUT_WIDTH /
// FRAC_BITS change.
//
//   addr = u[31 -: ADDR_BITS]
//   sign = addr[ADDR_BITS-1]           1 -> z >= 0 (upper half of (0,1))
//   j    = sign ? addr[low] : ~addr[low]
//   z    = sign ? +rom[j] : -rom[j]     (format Q(OUT_WIDTH-1-FRAC_BITS).FRAC_BITS)
//
// Latency: LATENCY cycles (1 = ROM + negate in one stage; 2 splits the ROM
// read and the conditional negate for timing). Throughput: one z per cycle.
// in_valid is just pipelined to out_valid; there is no back-pressure.
module gauss_lut #(
  parameter int ADDR_BITS = 10,
  parameter int OUT_WIDTH = 16,
  parameter int FRAC_BITS = 12,
  parameter int LATENCY   = 1
) (
  input  logic                        clk,
  input  logic                        rst_n,
  input  logic                        in_valid,
  input  logic [31:0]                 u,
  output logic                        out_valid,
  output logic signed [OUT_WIDTH-1:0] z
);
  localparam int MAG_BITS = ADDR_BITS - 1;

  logic [ADDR_BITS-1:0] addr;
  logic                 sign;
  logic [MAG_BITS-1:0]  j;
  logic [OUT_WIDTH-1:0] mag;

  assign addr = u[31 -: ADDR_BITS];
  assign sign = addr[ADDR_BITS-1];
  assign j    = sign ? addr[MAG_BITS-1:0] : ~addr[MAG_BITS-1:0];

  gauss_lut_rom #(.ADDR_BITS(ADDR_BITS), .OUT_WIDTH(OUT_WIDTH)) u_rom (.j(j), .mag(mag));

  generate
    if (LATENCY == 1) begin : g_lat1
      always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
          out_valid <= 1'b0;
          z         <= '0;
        end else begin
          out_valid <= in_valid;
          z         <= sign ? $signed(mag) : -$signed(mag);
        end
      end
    end else begin : g_lat2
      logic                 v_q;
      logic                 sign_q;
      logic [OUT_WIDTH-1:0] mag_q;
      always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
          v_q <= 1'b0; sign_q <= 1'b0; mag_q <= '0;
          out_valid <= 1'b0; z <= '0;
        end else begin
          v_q    <= in_valid;
          sign_q <= sign;
          mag_q  <= mag;
          out_valid <= v_q;
          z         <= sign_q ? $signed(mag_q) : -$signed(mag_q);
        end
      end
    end
  endgenerate

`ifndef SYNTHESIS
  // mag is a positive half-table entry; it must never use the sign bit.
  always_ff @(posedge clk) if (rst_n && in_valid) assert (mag[OUT_WIDTH-1] == 1'b0);
`endif
endmodule
